server:
  port: 2333
  address: 127.0.0.1
  sources:
    youtube: false
    bandcamp: true
    soundcloud: true
    twitch: true
    vimeo: true
    http: true
    local: false

spring:
  main:
    banner-mode: log

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true 