server:
  port: 2333
  address: 127.0.0.1
  sources:
    youtube: false  # Disable built-in YouTube source
    bandcamp: true
    soundcloud: true
    twitch: true
    vimeo: true
    http: true
    local: false

spring:
  main:
    banner-mode: log

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false  # Disable built-in YouTube source
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
    clientOptions:
      WEB:
        playback: true
        videoLoading: true
      WEBEMBEDDED:
        playlistLoading: true
        searching: true 