server:
  port: 2333
  address: 127.0.0.1

lavalink:
  server:
    password: "youshallnotpass" # For testing, you will change this locally to "test"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: false
      twitch: false
      vimeo: false
      http: true
      local: false
    soundcloudSearchEnabled: true

plugins:
  lavasrc:
    sources:
      spotify: true
      applemusic: false
      deezer: false
      youtube: true # Let the dedicated youtube-source plugin handle YouTube for playback
      # Add other lavasrc sources here and set to false if not needed
      # e.g., yandexmusic: false, flowerytts: false, vkmusic: false, tidal: false, qobuz: false, ytdlp: false
    spotify:
      clientId: "76990848ec57447695e5a4e8920bcd8b"
      clientSecret: "7026c2f1601e469d9a3c70807bc067c1"
      countryCode: "US"

# Default logging level is INFO, which is usually fine.
# logging:
#   level:
#     root: INFO
#     lavalink: INFO
