# Server configuration (Port, Address) - Ensure these match your bot's .env
server:
  port: 2333
  address: 127.0.0.1
  connectionTimeout: 30000  # 30 seconds connection timeout
  requestTimeout: 10000    # 10 seconds request timeout
  http2:
    enabled: false

# Spring Boot settings (usually fine as is)
spring:
  main:
    banner-mode: log # Optional: 'off' to disable the Spring Boot banner

# Lavalink server core settings
lavalink:
  server:
    password: "youshallnotpass" # IMPORTANT: Must match LAVALINK_PASSWORD in your .env
    sources:
      # Disable sources handled by plugins
      youtube: false
      # Enable desired built-in sources
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false # Keep local disabled for security unless specifically needed
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    # Other optional Lavalink settings (defaults are often fine)
    bufferDurationMs: 400
    # youtubePlaylistLoadLimit: 6 # This applies to the *built-in* source, less relevant when disabled
    playerUpdateInterval: 5 # In seconds
    # youtubeSearchEnabled: true # Also for built-in source, plugin handles its own searching
    soundcloudSearchEnabled: true # Keep true if you want Lavalink's scsearch: to work
    gc-warnings: true # Logs Java garbage collection warnings
    frameBufferDurationMs: 1000  # Increase frame buffer duration
    nullFrameTimeout: 10000      # Increase null frame timeout
    opusEncodingQuality: 10      # Higher quality opus encoding
    resamplingQuality: HIGH      # Better resampling quality
    trackStuckThresholdMs: 10000 # Increase stuck threshold
    useSeekGhosting: true       # Enable seek ghosting for smoother seeking

# --- Lavalink v4 Plugin Configuration ---
# Plugins listed here are configured *after* being loaded from the /plugins JAR directory
plugins:
  # YouTube Plugin (lavalink-devs/youtube-source) Configuration
  youtube:
    enabled: true # Master switch for the plugin
    # Use default configuration for YouTube

  # Lavasrc Plugin (Spotify, Apple Music, Deezer) Configuration
  lavasrc:
    # List of providers to load music from (Spotify is default if section exists)
    providers:
      # Explicitly list enabled providers if you want fine control, otherwise defaults are used
      - "spotify"     # Enable Spotify support
      # - "applemusic" # Uncomment if needed
      # - "deezer"    # Uncomment if needed

    # Spotify specific settings
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}      # Required: Add your Spotify Client ID here
      clientSecret: ${SPOTIFY_CLIENT_SECRET}  # Required: Add your Spotify Client Secret here
      countryCode: "US" # Optional: Use your country code to potentially bypass region locks
      playlistLoadLimit: 100 # Max tracks to load from a playlist
      albumLoadLimit: 100    # Max tracks to load from an album
      # searchLimit: 10 # Max results for Spotify search (if plugin supports it)
      cacheEnabled: true # Lavasrc internal caching (recommended)
      cacheSize: 1000
      cacheExpiry: 3600 # Seconds (1 hour)

    # Apple Music specific settings (Optional - remove if not used)
#    applemusic:
#      countryCode: "US"
      # mediaAPIToken: ${APPLE_MEDIA_API_TOKEN} # Requires separate token if needed
#      playlistLoadLimit: 100
#      albumLoadLimit: 100
      # searchLimit: 10
      # cacheEnabled: true
      # cacheSize: 1000
      # cacheExpiry: 3600

    # Deezer specific settings (Optional - remove if not used)
#    deezer:
      # masterDecryptionKey: ${DEEZER_MASTER_KEY} # Required for some functionality
#      playlistLoadLimit: 100
#      albumLoadLimit: 100
      # searchLimit: 10
      # cacheEnabled: true
      # cacheSize: 1000
      # cacheExpiry: 3600

# Logging configuration (Optional - Fine-tune Lavalink's logging)
logging:
  level:
    root: INFO
    lavalink: INFO